version: '3'

services:
  zookeeper:
    build: # Almost same as quay.io/debezium/zookeeper:2.3
      context: zookeeper
    healthcheck:
      test: "(echo mntr | nc 127.0.0.1 2181) || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:2.3
    ports:
      - 9092:9092
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: quay.io/debezium/example-mysql:2.3
    environment:
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_ROOT_PASSWORD=debezium
    ports:
      - 3306:3306
  connect:
    image: quay.io/debezium/connect:2.3
    depends_on:
      kafka:
        condition: service_started
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    ports:
    - 8083:8083    


